// Struct that maps error codes to error messages
typedef struct {
  DWORD error_code;
  char* error_message;
} error_map_t;

// Array of error codes taken from microsoft documentation for winerror.h
error_map_t error_map[] = {
  {0, "The operation completed successfully."},
  {1, "Incorrect function."},
  {2, "The system cannot find the file specified."},
  {3, "The system cannot find the path specified."},
  {4, "The system cannot open the file."},
  {5, "Access is denied."},
  {6, "The handle is invalid."},
  {7, "The storage control blocks were destroyed."},
  {8, "Not enough storage is available to process this command."},
  {9, "The storage control block address is invalid."},
  {10, "The environment is incorrect."},
  {11, "An attempt was made to load a program with an incorrect format."},
  {12, "The access code is invalid."},
  {13, "The data is invalid."},
  {14, "Not enough storage is available to complete this operation."},
  {15, "The system cannot find the drive specified."},
  {16, "The directory cannot be removed."},
  {17, "The system cannot move the file to a different disk drive."},
  {18, "There are no more files."},
  {19, "The media is write-protected."},
  {20, "The system cannot find the device specified."},
  {21, "The device is not ready."},
  {22, "The device does not recognize the command."},
  {23, "Data error (cyclic redundancy check)."},
  {24, "The program issued a command but the command length is incorrect."},
  {25, "The drive cannot locate a specific area or track on the disk."},
  {26, "The specified disk or diskette cannot be accessed."},
  {27, "The drive cannot find the sector requested."},
  {28, "The printer is out of paper."},
  {29, "The system cannot write to the specified device."},
  {30, "The system cannot read from the specified device."},
  {31, "A device attached to the system is not functioning."},
  {32, "The process cannot access the file because it is being used by another process."},
  {33, "The process cannot access the file because another process has locked a portion of the file."},
  {34, "The wrong diskette is in the drive. Insert %2 (Volume Serial Number: %3) into drive %1."},
  {36, "Too many files opened for sharing."},
  {38, "Reached the end of the file."},
  {39, "The disk is full."},
  {50, "The request is not supported."},
  {51, "Windows cannot find the network path. Verify that the network path is correct and the destination computer is not busy or turned off. If Windows still cannot find the network path, contact your network administrator."},
  {52, "You were not connected because a duplicate name exists on the network. If joining a domain, go to System in Control Panel to change the computer name and try again. If joining a workgroup, choose another workgroup name."},
  {53, "The network path was not found."},
  {54, "The network is busy."},
  {55, "The specified network resource or device is no longer available."},
  {56, "The network BIOS command limit has been reached."},
  {57, "A network adapter hardware error occurred."},
  {58, "The specified server cannot perform the requested operation."},
  {59, "An unexpected network error occurred."},
  {60, "The remote adapter is not compatible."},
  {61, "The printer queue is full."},
  {62, "Space to store the file waiting to be printed is not available on the server."},
  {63, "Your file waiting to be printed was deleted."},
  {64, "The specified network name is no longer available."},
  {65, "Network access is denied."},
  {66, "The network resource type is not correct."},
  {67, "The network name cannot be found."},
  {68, "The name limit for the local computer network adapter card was exceeded."},
  {69, "The network BIOS session limit was exceeded."},
  {70, "The remote server has been paused or is in the process of being started."},
  {71, "No more connections can be made to this remote computer at this time because there are already as many connections as the computer can accept."},
  {72, "The specified printer or disk device has been paused."},
  {80, "The file exists."},
  {82, "The directory or file cannot be created."},
  {83, "Fail on INT 24."},
  {84, "Storage to process this request is not available."},
  {85, "The local device name is already in use."},
  {86, "The specified network password is not correct."},
  {87, "The parameter is incorrect."},
  {88, "A write fault occurred on the network."},
  {89, "The system cannot start another process at this time."},
  {100, "Cannot create another system semaphore."},
  {101, "The exclusive semaphore is owned by another process."},
  {102, "The semaphore is set and cannot be closed."},
  {103, "The semaphore timeout period has expired."},
  {104, "The semaphore has been abandoned."},
  {105, "The semaphore was released while waiting."},
  {106, "Cannot request exclusive semaphores at interrupt time."},
  {107, "The previous ownership of this semaphore has ended."},
  {108, "Insert the diskette for drive %1."},
  {109, "The program stopped because an alternate diskette was not inserted."},
  {110, "The disk is in use or locked by another process."},
  {111, "The pipe has been ended."},
  {112, "The system cannot open the device or file specified."},
  {113, "The file name is too long."},
  {114, "Cannot request a METAFILEPICT handle from the display."},
  {117, "The RPC server is too busy to complete this operation."},
  {118, "No more bindings."},
  {119, "The system cannot start another process at this time."},
  {120, "There are no child processes to wait for."},
  {121, "The %1 application cannot be run in Win32 mode."},
  {122, "Attempt to use a file handle to an open disk partition for an operation other than raw disk I/O."},
  {123, "The filename, directory name, or volume label syntax is incorrect."},
  {124, "The system call level is not correct."},
  {125, "The disk has no volume label."},
  {126, "The specified module could not be found."},
  {127, "The specified procedure could not be found."},
  {128, "There are no child processes to wait for."},
  {129, "The %1 application cannot be run in Win32 mode."},
  {130, "Attempt to use a file handle to an open file for an operation other than raw disk I/O."},
  {131, "An attempt was made to move the file pointer before the beginning of the file."},
  {132, "The file pointer cannot be set on the specified device or file."},
  {133, "A JOIN or SUBST command cannot be used for a drive that contains previously joined drives."},
  {134, "An attempt was made to use a JOIN or SUBST command on a drive that has already been joined."},
  {135, "An attempt was made to use a JOIN or SUBST command on a drive that has already been substituted."},
  {136, "The system tried to delete the JOIN of a drive that is not joined."},
  {137, "The system tried to delete the substitution of a drive that is not substituted."},
  {138, "The system tried to join a drive to a directory on a joined drive."},
  {139, "The system tried to substitute a drive to a directory on a substituted drive."},
  {140, "The system tried to join a drive to a directory on a substituted drive."},
  {141, "The system tried to SUBST a drive to a directory on a joined drive."},
  {142, "The system cannot perform a JOIN or SUBST at this time."},
  {143, "The system cannot join or substitute a drive to or for a directory on the same drive."},
  {144, "The directory is not a subdirectory of the root directory."},
  {145, "The directory is not empty."},
  {146, "The path specified is being used in a substitute."},
  {147, "Not enough resources are available to process this command."},
  {148, "The path specified cannot be used at this time."},
  {149, "An attempt was made to join or substitute a drive for which a directory on the drive is the target of a previous substitute."},
  {150, "System trace information was not specified in your CONFIG.SYS file, or tracing is disallowed."},
  {151, "The number of specified semaphore events for DosMuxSemWait is not correct."},
  {152, "DosMuxSemWait did not execute; too many semaphores are already set."},
  {153, "The DosMuxSemWait list is not correct."},
  {154, "The volume label you entered exceeds the label character limit of the target file system."},
  {155, "Cannot create another thread."},
  {156, "The recipient process has refused the signal."},
  {157, "The segment is already discarded and cannot be locked."},
  {158, "The segment is already unlocked."},
  {159, "The address for the thread ID is not correct."},
  {160, "One or more arguments are not correct."},
  {161, "The specified path is invalid."},
  {162, "A signal is already pending."},
  {164, "No more threads can be created in the system."},
  {167, "Unable to lock a region of a file."},
  {170, "The requested resource is in use."},
  {173, "A lock request was not outstanding for the supplied cancel region."},
  {174, "The file system does not support atomic changes to the lock type."},
  {180, "The system detected a segment number that was not correct."},
  {182, "The operating system cannot run %1."},
  {183, "Cannot create a file when that file already exists."},
  {186, "The flag passed is not correct."},
  {187, "The specified system semaphore name was not found."},
  {188, "The operating system cannot run %1."},
  {189, "The operating system cannot run %1."},
  {190, "The operating system cannot run %1."},
  {191, "Cannot run %1 in Win32 mode."},
  {192, "The operating system cannot run %1."},
  {193, "The operating system cannot run %1."},
  {194, "The operating system cannot run %1."},
  {195, "The operating system cannot run this application program."},
  {196, "The operating system is not presently configured to run this application."},
  {197, "The operating system cannot run %1."},
  {198, "The operating system cannot run this application program."},
  {199, "The operating system is not presently configured to run this application."},
  {200, "The code segment cannot be greater than or equal to 64K."},
  {201, "The operating system cannot run %1."},
  {202, "The operating system cannot run %1."},
  {203, "The system could not find the environment option that was entered."},
  {205, "No process in the command subtree has a signal handler."},
  {206, "The filename or extension is too long."},
  {207, "The ring 2 stack is in use by another thread."},
  {208, "The global filename characters, * or ?, are entered incorrectly or too many global filename characters are specified."},
  {209, "The signal being posted is not correct."},
  {210, "The signal handler cannot be set."},
  {212, "The segment is locked and cannot be reallocated."},
  {214, "Too many dynamic-link modules are attached to this program or dynamic-link module."},
  {215, "Cannot nest calls to LoadModule."},
  {216, "The version of %1 is not compatible with the version you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."},
  {217, "The image file %1 is signed, unable to modify."},
  {218, "The image file %1 is strong signed, unable to modify."},
  {230, "The pipe state is invalid."},
  {231, "All pipe instances are busy."},
  {232, "The pipe is being closed."},
  {233, "No process is on the other end of the pipe."},
  {234, "More data is available."},
  {240, "The session was canceled."},
  {254, "The specified extended attribute name was invalid."},
  {255, "The extended attributes are inconsistent."},
  {258, "The wait operation timed out."},
  {259, "No more data is available."},
  {266, "The copy functions cannot be used."},
  {267, "The directory name is invalid."},
  {275, "The extended attributes did not fit in the buffer."},
  {276, "The extended attribute file on the mounted file system is corrupt."},
  {277, "The extended attribute table file is full."},
  {278, "The specified extended attribute handle is invalid."},
  {282, "The mounted file system does not support extended attributes."},
  {288, "Attempt to release mutex not owned by caller."},
  {298, "Too many posts were made to a semaphore."},
  {299, "Only part of a ReadProcessMemory or WriteProcessMemory request was completed."},
  {300, "The oplock request is denied."},
  {301, "An invalid oplock acknowledgment was received by the system."},
  {302, "The volume is too fragmented to complete this operation."},
  {303, "The file cannot be opened because it is in the process of being deleted."},
  {317, "The system cannot find message text for message number 0x%1 in the message file for %2."},
  {318, "The scope specified was not found."},
  {487, "Attempt to access invalid address."},
  {534, "Arithmetic result exceeded 32 bits."},
  {535, "There is a process on other end of the pipe."},
  {536, "Waiting for a process to open the other end of the pipe."},
  {994, "Access to the extended attribute was denied."},
  {995, "The I/O operation has been aborted because of either a thread exit or an application request."},
  {996, "Overlapped I/O event is not in a signaled state."},
  {997, "Overlapped I/O operation is in progress."},
  {998, "Invalid access to memory location."},
  {999, "Error performing inpage operation."},
  {1001, "Recursion too deep; the stack overflowed."},
  {1002, "The window cannot act on the sent message."},
  {1003, "Cannot complete this function."},
  {1004, "Invalid flags."},
  {1005, "The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that the volume is not corrupted."},
  {1006, "The volume for a file has been externally altered such that the opened file is no longer valid."},
  {1007, "The requested operation cannot be performed in full-screen mode."},
  {1008, "An attempt was made to reference a token that does not exist."},
  {1009, "The configuration registry database is corrupt."},
  {1010, "The configuration registry key is invalid."},
  {1011, "The configuration registry key could not be opened."},
  {1012, "The configuration registry key could not be read."},
  {1013, "The configuration registry key could not be written."},
  {1014, "One of the files in the registry database had to be recovered by use of a log or alternate copy. The recovery was successful."},
  {1015, "The registry is corrupted. The structure of one of the files that contains registry data is corrupted, or the system's image of the file in memory is corrupted, or the file could not be recovered because the alternate copy or log was absent or corrupted."},
  {1016, "An I/O operation initiated by the registry failed unrecoverably. The registry could not read in, or write out, or flush, one of the files that contain the system's image of the registry."},
  {1017, "The system has attempted to load or restore a file into the registry, but the specified file is not in a registry file format."},
  {1018, "Illegal operation attempted on a registry key that has been marked for deletion."},
  {1019, "System could not allocate the required space in a registry log."},
  {1020, "Cannot create a symbolic link in a registry key that already has subkeys or values."},
  {1021, "Cannot create a stable subkey under a volatile parent key."},
  {1022, "A notify change request is being completed and the information is not being returned in the caller's buffer. The caller now needs to enumerate the files to find the changes."},
  
  // Add more error codes and messages here as needed
};

// Number of elements in the error map array
#define NUM_ERROR_CODES (sizeof(error_map) / sizeof(error_map_t))