#![allow(dead_code)]
pub struct ErrorMap {
    pub error_code: u32,
    pub error_message: &'static str,
  }
  
  pub static ERROR_MAP: [ErrorMap; 210] = [
    ErrorMap { error_code: 0, error_message: "The operation completed successfully." },
    ErrorMap { error_code: 1, error_message: "Incorrect function." },
    ErrorMap { error_code: 2, error_message: "The system cannot find the file specified." },
    ErrorMap { error_code: 3, error_message: "The system cannot find the path specified." },
    ErrorMap { error_code: 4, error_message: "The system cannot open the file." },
    ErrorMap { error_code: 5, error_message: "Access is denied." },
    ErrorMap { error_code: 6, error_message: "The handle is invalid." },
    ErrorMap { error_code: 7, error_message: "The storage control blocks were destroyed." },
    ErrorMap { error_code: 8, error_message: "Not enough storage is available to process this command." },
    ErrorMap { error_code: 9, error_message: "The storage control block address is invalid." },
    ErrorMap { error_code: 10, error_message: "The environment is incorrect." },
    ErrorMap { error_code: 11, error_message: "An attempt was made to load a program with an incorrect format." },
    ErrorMap { error_code: 12, error_message: "The access code is invalid." },
    ErrorMap { error_code: 13, error_message: "The data is invalid." },
    ErrorMap { error_code: 14, error_message: "Not enough storage is available to complete this operation." },
    ErrorMap { error_code: 15, error_message: "The system cannot find the drive specified." },      
    ErrorMap { error_code: 16, error_message: "The directory cannot be removed." },
    ErrorMap { error_code: 17, error_message: "The system cannot move the file to a different disk drive." },
    ErrorMap { error_code: 18, error_message: "There are no more files." },
    ErrorMap { error_code: 19, error_message: "The media is write protected." },
    ErrorMap { error_code: 20, error_message: "The system cannot find the device specified." },
    ErrorMap { error_code: 21, error_message: "The device is not ready." },
    ErrorMap { error_code: 22, error_message: "The device does not recognize the command." },
    ErrorMap { error_code: 23, error_message: "Data error (cyclic redundancy check)." },
    ErrorMap { error_code: 24, error_message: "The program issued a command but the command length is incorrect." },
    ErrorMap { error_code: 25, error_message: "The drive cannot locate a specific area or track on the disk." },
    ErrorMap { error_code: 26, error_message: "The specified disk or diskette cannot be accessed." },
    ErrorMap { error_code: 27, error_message: "The drive cannot find the sector requested." },
    ErrorMap { error_code: 28, error_message: "The printer is out of paper." },
    ErrorMap { error_code: 29, error_message: "The system cannot write to the specified device." },
    ErrorMap { error_code: 30, error_message: "The system cannot read from the specified device." },
    ErrorMap { error_code: 31, error_message: "A device attached to the system is not functioning." },
    ErrorMap { error_code: 32, error_message: "The process cannot access the file because it is being used by another process." },
    ErrorMap { error_code: 33, error_message: "The process cannot access the file because another process has locked a portion of the file." },
    ErrorMap { error_code: 34, error_message: "The wrong diskette is in the drive. Insert %2 (Volume Serial Number: %3) into drive %1." },
    ErrorMap { error_code: 36, error_message: "Too many files opened for sharing." },
    ErrorMap { error_code: 38, error_message: "Reached the end of the file." },
    ErrorMap { error_code: 39, error_message: "The disk is full." },
    ErrorMap { error_code: 50, error_message: "The request is not supported." },
    ErrorMap { error_code: 51, error_message: "The remote computer is not available." },
    ErrorMap { error_code: 52, error_message: "A duplicate name exists on the network." },
    ErrorMap { error_code: 53, error_message: "The network path was not found." },
    ErrorMap { error_code: 54, error_message: "The network is busy." },
    ErrorMap { error_code: 55, error_message: "The specified network resource or device is no longer available." },
    ErrorMap { error_code: 56, error_message: "The network BIOS command limit has been reached." },
    ErrorMap { error_code: 57, error_message: "A network adapter hardware error occurred." },
    ErrorMap { error_code: 58, error_message: "The specified server cannot perform the requested operation." },
    ErrorMap { error_code: 59, error_message: "An unexpected network error occurred." },
    ErrorMap { error_code: 60, error_message: "The remote adapter is not compatible." },
    ErrorMap { error_code: 61, error_message: "The printer queue is full." },
    ErrorMap { error_code: 62, error_message: "Space to store the file waiting to be printed is not available on the server." },
    ErrorMap { error_code: 63, error_message: "Your file waiting to be printed was deleted." },
    ErrorMap { error_code: 64, error_message: "The specified network name is no longer available." },
    ErrorMap { error_code: 65, error_message: "Network access is denied." },
    ErrorMap { error_code: 66, error_message: "The network resource type is not correct." },
    ErrorMap { error_code: 67, error_message: "The network name cannot be found." },
    ErrorMap { error_code: 68, error_message: "The name limit for the local computer network adapter card was exceeded." },
    ErrorMap { error_code: 69, error_message: "The network BIOS session limit was exceeded." },
    ErrorMap { error_code: 70, error_message: "The remote server has been paused or is in the process of being started." },
    ErrorMap { error_code: 71, error_message: "No more connections can be made to this remote computer at this time because there are already as many connections as the computer can accept." },
    ErrorMap { error_code: 72, error_message: "The specified printer or disk device has been paused." },
    ErrorMap { error_code: 80, error_message: "The file exists." },
    ErrorMap { error_code: 82, error_message: "The directory or file cannot be created." },
    ErrorMap { error_code: 83, error_message: "Fail on INT 24." },
    ErrorMap { error_code: 84, error_message: "Storage to process this request is not available." },
    ErrorMap { error_code: 85, error_message: "The local device name is already in use." },
    ErrorMap { error_code: 86, error_message: "The specified network password is not correct." },
    ErrorMap { error_code: 87, error_message: "The parameter is incorrect." },
    ErrorMap { error_code: 88, error_message: "A write fault occurred on the network." },
    ErrorMap { error_code: 89, error_message: "The system cannot start another process at this time." },
    ErrorMap { error_code: 100, error_message: "Cannot create another system semaphore." },
    ErrorMap { error_code: 101, error_message: "The exclusive semaphore is owned by another process." },
    ErrorMap { error_code: 102, error_message: "The semaphore is set and cannot be closed." },
    ErrorMap { error_code: 103, error_message: "The semaphore cannot be set again." },
    ErrorMap { error_code: 104, error_message: "Cannot request exclusive semaphores at interrupt time." },
    ErrorMap { error_code: 105, error_message: "The previous ownership of this semaphore has ended." },
    ErrorMap { error_code: 106, error_message: "Insert the diskette for drive %1." },
    ErrorMap { error_code: 107, error_message: "The program stopped because an alternate diskette was not inserted." },
    ErrorMap { error_code: 108, error_message: "The disk is in use or locked by another process." },
    ErrorMap { error_code: 109, error_message: "The pipe has been ended." },
    ErrorMap { error_code: 110, error_message: "The system cannot open the device or file specified." },
    ErrorMap { error_code: 111, error_message: "The file name is too long." },
    ErrorMap { error_code: 112, error_message: "There is not enough space on the disk." },
    ErrorMap { error_code: 113, error_message: "No more internal file identifiers available." },
    ErrorMap { error_code: 114, error_message: "The target internal file identifier is incorrect." },
    ErrorMap { error_code: 117, error_message: "The IOCTL call made by the application program is not correct." },
    ErrorMap { error_code: 118, error_message: "The verify-on-write switch parameter value is not correct." },
    ErrorMap { error_code: 119, error_message: "The system does not support the command requested." },
    ErrorMap { error_code: 120, error_message: "This function is not supported on this system." },
    ErrorMap { error_code: 121, error_message: "The semaphore timeout period has expired." },
    ErrorMap { error_code: 122, error_message: "The data area passed to a system call is too small." },
    ErrorMap { error_code: 123, error_message: "The filename, directory name, or volume label syntax is incorrect." },
    ErrorMap { error_code: 124, error_message: "The system call level is not correct." },
    ErrorMap { error_code: 125, error_message: "The disk has no volume label." },
    ErrorMap { error_code: 126, error_message: "The specified module could not be found." },
    ErrorMap { error_code: 127, error_message: "The specified procedure could not be found." },
    ErrorMap { error_code: 128, error_message: "There are no child processes to wait for." },
    ErrorMap { error_code: 129, error_message: "The %1 application cannot be run in Win32 mode." },
    ErrorMap { error_code: 130, error_message: "Attempt to use a file handle to an open disk partition for an operation other than raw disk I/O." },
    ErrorMap { error_code: 131, error_message: "An attempt was made to move the file pointer before the beginning of the file." },
    ErrorMap { error_code: 132, error_message: "The file pointer cannot be set on the specified device or file." },
    ErrorMap { error_code: 133, error_message: "A JOIN or SUBST command cannot be used for a drive that contains previously joined drives." },
    ErrorMap { error_code: 134, error_message: "An attempt was made to use a JOIN or SUBST command on a drive that has already been joined." },
    ErrorMap { error_code: 135, error_message: "An attempt was made to use a JOIN or SUBST command on a drive that has already been substituted." },
    ErrorMap { error_code: 136, error_message: "The system tried to delete the JOIN of a drive that is not joined." },
    ErrorMap { error_code: 137, error_message: "The system tried to delete the substitution of a drive that is not substituted." },
    ErrorMap { error_code: 138, error_message: "The system tried to join a drive to a directory on a joined drive." },
    ErrorMap { error_code: 139, error_message: "The system tried to substitute a drive to a directory on a substituted drive." },
    ErrorMap { error_code: 140, error_message: "The system tried to join a drive to a directory on a substituted drive." },
    ErrorMap { error_code: 141, error_message: "The system tried to SUBST a drive to a directory on a joined drive." },
    ErrorMap { error_code: 142, error_message: "The system cannot perform a JOIN or SUBST at this time." },
    ErrorMap { error_code: 143, error_message: "The system cannot join or substitute a drive to or for a directory on the same drive." },
    ErrorMap { error_code: 144, error_message: "The directory is not a subdirectory of the root directory." },
    ErrorMap { error_code: 145, error_message: "The directory is not empty." },
    ErrorMap { error_code: 146, error_message: "The path specified is being used in a substitute." },
    ErrorMap { error_code: 147, error_message: "Not enough resources are available to process this command." },
    ErrorMap { error_code: 148, error_message: "The path specified cannot be used at this time." },
    ErrorMap { error_code: 149, error_message: "An attempt was made to join or substitute a drive for which a directory on the drive is the target of a previous substitute." },
    ErrorMap { error_code: 150, error_message: "System trace information was not specified in your CONFIG.SYS file, or tracing is disallowed." },
    ErrorMap { error_code: 151, error_message: "The number of specified semaphore events for DosMuxSemWait is not correct." },
    ErrorMap { error_code: 152, error_message: "DosMuxSemWait did not execute; too many semaphores are already set." },
    ErrorMap { error_code: 153, error_message: "The DosMuxSemWait list is not correct." },
    ErrorMap { error_code: 154, error_message: "The volume label you entered exceeds the label character limit of the target file system." },
    ErrorMap { error_code: 155, error_message: "Cannot create another thread." },
    ErrorMap { error_code: 156, error_message: "The recipient process has refused the signal." },
    ErrorMap { error_code: 157, error_message: "The segment is already discarded and cannot be locked." },
    ErrorMap { error_code: 158, error_message: "The segment is already unlocked." },
    ErrorMap { error_code: 159, error_message: "The address for the thread ID is not correct." },
    ErrorMap { error_code: 160, error_message: "One or more arguments are not correct." },
    ErrorMap { error_code: 161, error_message: "The specified path is invalid." },
    ErrorMap { error_code: 162, error_message: "A signal is already pending." },
    ErrorMap { error_code: 164, error_message: "No more threads can be created in the system." },
    ErrorMap { error_code: 167, error_message: "Unable to lock a region of a file." },
    ErrorMap { error_code: 170, error_message: "The requested resource is in use." },
    ErrorMap { error_code: 173, error_message: "A lock request was not outstanding for the supplied cancel region." },
    ErrorMap { error_code: 174, error_message: "The file system does not support atomic changes to the lock type." },
    ErrorMap { error_code: 180, error_message: "The system detected a segment number that was not correct." },
    ErrorMap { error_code: 182, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 183, error_message: "Cannot create a file when that file already exists." },
    ErrorMap { error_code: 186, error_message: "The flag passed is not correct." },
    ErrorMap { error_code: 187, error_message: "The specified system semaphore name was not found." },
    ErrorMap { error_code: 188, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 189, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 190, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 191, error_message: "Cannot run %1 in Win32 mode." },
    ErrorMap { error_code: 192, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 193, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 194, error_message: "The operating system cannot run this application program." },
    ErrorMap { error_code: 195, error_message: "The operating system is not presently configured to run this application." },
    ErrorMap { error_code: 196, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 197, error_message: "The operating system cannot run this application program." },
    ErrorMap { error_code: 198, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 199, error_message: "The operating system cannot run this application program." },
    ErrorMap { error_code: 200, error_message: "The code segment cannot be greater than or equal to 64K." },
    ErrorMap { error_code: 201, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 202, error_message: "The operating system cannot run %1." },
    ErrorMap { error_code: 203, error_message: "The system could not find the environment option that was entered." },
    ErrorMap { error_code: 205, error_message: "No process in the command subtree has a signal handler." },
    ErrorMap { error_code: 206, error_message: "The filename or extension is too long." },
    ErrorMap { error_code: 207, error_message: "The ring 2 stack is in use." },
    ErrorMap { error_code: 208, error_message: "The global filename characters, * or ?, are entered incorrectly or too many global filename characters are specified." },
    ErrorMap { error_code: 209, error_message: "The signal being posted is not correct." },
    ErrorMap { error_code: 210, error_message: "The signal handler cannot be set." },
    ErrorMap { error_code: 212, error_message: "The segment is locked and cannot be reallocated." },
    ErrorMap { error_code: 214, error_message: "Too many dynamic-link modules are attached to this program or dynamic-link module." },
    ErrorMap { error_code: 215, error_message: "Cannot nest calls to LoadModule." },
    ErrorMap { error_code: 216, error_message: "The version of %1 is not compatible with the version you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher." },
    ErrorMap { error_code: 217, error_message: "The image file %1 is signed, unable to modify." },
    ErrorMap { error_code: 218, error_message: "The image file %1 is strong signed, unable to modify." },
    ErrorMap { error_code: 230, error_message: "The pipe state is invalid." },
    ErrorMap { error_code: 231, error_message: "All pipe instances are busy." },
    ErrorMap { error_code: 232, error_message: "The pipe is being closed." },
    ErrorMap { error_code: 233, error_message: "No process is on the other end of the pipe." },
    ErrorMap { error_code: 234, error_message: "More data is available." },
    ErrorMap { error_code: 240, error_message: "The session was canceled." },
    ErrorMap { error_code: 254, error_message: "The specified extended attribute name was invalid." },
    ErrorMap { error_code: 255, error_message: "The extended attributes are inconsistent." },
    ErrorMap { error_code: 258, error_message: "The wait operation timed out." },
    ErrorMap { error_code: 259, error_message: "No more data is available." },
    ErrorMap { error_code: 266, error_message: "The copy functions cannot be used." },
    ErrorMap { error_code: 267, error_message: "The directory name is invalid." },
    ErrorMap { error_code: 275, error_message: "The extended attributes did not fit in the buffer." },
    ErrorMap { error_code: 276, error_message: "The extended attribute file on the mounted file system is corrupt." },
    ErrorMap { error_code: 277, error_message: "The extended attribute table file is full." },
    ErrorMap { error_code: 278, error_message: "The specified extended attribute handle is invalid." },
    ErrorMap { error_code: 282, error_message: "The mounted file system does not support extended attributes." },
    ErrorMap { error_code: 288, error_message: "Attempt to release mutex not owned by caller." },
    ErrorMap { error_code: 298, error_message: "Too many posts were made to a semaphore." },
    ErrorMap { error_code: 299, error_message: "Only part of a ReadProcessMemory or WriteProcessMemory request was completed." },
    ErrorMap { error_code: 300, error_message: "The oplock request is denied." },
    ErrorMap { error_code: 301, error_message: "An invalid oplock acknowledgment was received by the system." },
    ErrorMap { error_code: 302, error_message: "The volume is too fragmented to complete this operation." },
    ErrorMap { error_code: 303, error_message: "The file cannot be opened because it is in the process of being deleted." },
    ErrorMap { error_code: 304, error_message: "Short name settings may not be changed on this volume due to the global registry setting." },
    ErrorMap { error_code: 305, error_message: "Short names are not enabled on this volume." },
    ErrorMap { error_code: 306, error_message: "The security stream for the given volume is in an inconsistent state. Please run CHKDSK on the volume." },
    ErrorMap { error_code: 307, error_message: "A requested file lock operation cannot be processed due to an invalid byte range." },
    ErrorMap { error_code: 308, error_message: "The subsystem needed to support the image type is not present." },
    ErrorMap { error_code: 309, error_message: "The specified file already has a notification GUID associated with it." },
    ErrorMap { error_code: 310, error_message: "An invalid exception handler routine has been detected." },
    ErrorMap { error_code: 311, error_message: "Duplicate privileges were specified for the token." },
    ErrorMap { error_code: 312, error_message: "No ranges for the specified operation were able to be processed." },
    ErrorMap { error_code: 313, error_message: "Operation is not allowed on a file system internal file." },
    ErrorMap { error_code: 314, error_message: "The physical resources of this disk have been exhausted." },
    ErrorMap { error_code: 315, error_message: "The token representing the data is invalid." },
    ErrorMap { error_code: 316, error_message: "The device does not support the command feature." },
    ErrorMap { error_code: 317, error_message: "The system cannot find message text for message number 0x%1 in the message file for %2." },
    ErrorMap { error_code: 318, error_message: "The scope specified was not found." },
    ErrorMap { error_code: 319, error_message: "The Central Access Policy specified is not defined on the target machine." },
    ErrorMap { error_code: 320, error_message: "The Central Access Policy obtained from Active Directory is invalid." },
//todo: add more error codes
  ];

  //a const cannot reference static data, so we need to create a const that is the length of the array
pub const ERROR_MAP_LENGTH: usize = 210;
  
